version: '3.8'
services:
  backend:
    build:
      context: ./tamilboomi-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongodb
    #   - redis
    # environment:

  frontend:
    build:
      context: ./tamilboomi-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SERVER_URI: "http://localhost:8000/api/v1/"

